name: Phishing Report
description: Create a phishing (or impersonation) report.
title: "Phishing | example.com"
labels:
  - "false positive"
assignees:
  - funilrys
  - mitchellkrogza
projects:
  - Phishing-Database/2
body:
  - type: markdown
    attributes:
      value: |+
        Thank you for submitting a phishing report.

        We understand that dealing with phishing can be stressful and disruptive for webmasters, developers, and service owners. Please be patient — one of our team members will review your report as soon as possible. Providing detailed information will help us investigate and resolve the issue more efficiently.

        Please note:
          - We are a small team and may not respond immediately.
          - We may request additional information to better understand your report.
          - Your issue may be moved to another repository for further investigation.

        Your reports help us improve the Phishing Database.

        If you have questions or need assistance, please visit our [Discussions](https://github.com/Phishing-Database/dev-center/discussions) section.

        — The Phishing Database Project Team

  - type: textarea
    id: target-subjects
    attributes:
      label: What are the subjects of the phishing (domains, URLs or IPs)?
      description: |
        Please list any domains, URLs or IPs that you believe are performing phishing or impersonation attacks against you or others.

        **WARNINGS:**

          - **Please prefix any subjects with backticks (`) to prevent them from becoming clickable.**
          - Please do NOT provide any personal information, such as your own IP address or email address.
          - Please warn with "NSFW" where applicable.
          - If you are submitting an IP address, please also provide the CIDR notation (e.g. `/32`) - if applicable.

        Please warn with "NSFW" where applicable.
      placeholder: |
        * `example.com`
        * `sub.example.com`
        * `https://example.com/page`
        * `https://sub.example.com/page`
        * **NSFW** `example.com`
        * `192.168.0.0/16`
    validations:
      required: true

  - type: textarea
    id: target-impersonated
    attributes:
      label: What are the impersonated domains?
      description: |
        Please list any domains that you believe are being impersonated by the phishing subjects.
      placeholder: |
        * `example.org`
        * `sub.example.org`
        * `https://example.org/page`
        * `https://sub.example.org/page`
    validations:
      required: true

  - type: textarea
    id: discovery
    attributes:
      label: Where or how did you discover this phishing?
      description: Please provide any information that may help us understand how you discovered or how you were targeted by this phishing.
      placeholder: |
        I discovered this phishing by...
        I was targeted by this phishing by...
    validations:
      required: true

  - type: textarea
    id: screenshot
    attributes:
      label: Do you have a screenshot?
      description: |
        Please provide a screenshot of the phishing site and the impersonated domain.

        Please note that there need to be at least one blank line separating before and after the image line.
        To add an image, use the following code: `![Screenshot of phishing](https://example.com/path/to/image.png)`
      placeholder: |
        <details><summary>Screenshot</summary>


        </details>
      value: |
        <details><summary>Screenshot</summary>


        </details>
    validations:
      required: false

  - type: textarea
    id: related-external-source
    attributes:
      label: Related external source
      description: |
        Please provide any relevant links to your existing blacklisting requests or other sources.

        One link per line.
      placeholder: |
        * https://sub.example.co.uk/page
    validations:
      required: false

  - type: textarea
    id: more-info
    attributes:
      label: Additional Information or Context
      description: Is there anything else you'd like to add?
      placeholder: |
        I have also noticed that...
    validations:
      required: false
